blank_issues_enabled: false
contact_links:
  - name: â“ Have a question or need help?
    url: https://community.redwoodjs.com/new-topic?category=get-help-and-help-others
    about: >
      Have a question about the way Redwood works?
      Or not sure if you're doing something right?
      Ask us over on the forums
