[dev]
  command = "cameronjs dev"
  publish = "publish"
  port = 8080

[build]
  command = "yarn install && yarn build"
  publish = "publish"
  functions = "functions"

# For more settings see https://www.netlify.com/docs/netlify-toml-reference/#post-processing
[build.processing]
  skip_processing = false
[build.processing.css]
  minify = true
[build.processing.js]
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[context.production]
  environment = { NODE_ENV = "production"}

[context.branch-deploy]
  environment = { NODE_ENV = "production" }

[[redirects]]
  from = "/docs"
  to = "/docs/introduction"
  status = 301
  force = true

[[headers]]
  for = "/docs/introduction"
  [headers.values]
    Turbolinks-Location = "/docs/introduction"

[[redirects]]
  from = "/docs/flash-messaging-bus"
  to = "/docs/toast-notifications"
  status = 301
  force = true

[[headers]]
  for = "/docs/toast-notifications"
  [headers.values]
    Turbolinks-Location = "/docs/toast-notifications"

[[redirects]]
  from = "/cookbook"
  to = "/cookbook/disable-api-database"
  status = 301
  force = true

[[headers]]
  for = "/cookbook/disable-api-database"
  [headers.values]
    Turbolinks-Location = "/cookbook/disable-api-database"

[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  force = true

[[headers]]
  for = "/"
  [headers.values]
    Turbolinks-Location = "/"

[[redirects]]
  from = "/guides/introduction"
  to = "/docs/introduction"

[[redirects]]
from = "/guides/authentication"
to = "/docs/authentication"

[[redirects]]
from = "/home"
to = "/"

[[redirects]]
  from = "/guides/assets-and-files"
  to = "/docs/assets-and-files"

[[redirects]]
  from = "/guides/builds"
  to = "/docs/builds"

[[redirects]]
  from = "/guides/command-line-interface"
  to = "/docs/cli-commands"

[[redirects]]
from = "/reference/command-line-interface"
to = "/docs/cli-commands"

[[redirects]]
from = "/guides/connection-pooling"
to = "/docs/connection-pooling"

[[redirects]]
from = "/guides/contributing"
to = "/docs/contributing"

[[redirects]]
from = "/guides/redwood-s-http-server-for-serverless-functions"
to = "/docs/serverless-functions"

[[redirects]]
from = "/guides/environment-variables"
to = "/docs/environment-variables"

[[redirects]]
from = "/guides/local-postgres-setup"
to = "/docs/local-postgres-setup"

[[redirects]]
from = "/guides/redwood-router"
to = "/docs/redwood-router"

[[redirects]]
from = "/guides/webpack-config"
to = "/docs/webpack-configuration"

[[redirects]]
from = "/reference/app-configuration-redwood-toml"
to = "/docs/app-configuration-redwood-toml"

[[redirects]]
from = "/reference/redwood-form"
to = "/docs/form"

[[redirects]]
from = "/docs/type-script"
to = "/docs/typescript"

[[redirects]]
from ="/good-first-issue"
to ="https://github.com/redwoodjs/redwood/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22"

[[redirects]]
from = "/docs/mocking-graph-ql-requests"
to = "/docs/mocking-graphql-requests"

[[redirects]]
from = "/docs/form"
to = "/docs/forms"

[[redirects]]
from = "/cookbook/mocking-graph-ql-in-storybook"
to = "/cookbook/mocking-graphql-in-storybook"

[[redirects]]
from = "/cookbook/go-true-auth"
to = "/cookbook/gotrue-auth"

[[redirects]]
  from = "/newsletter"
  to = "https://redwoodjs.us19.list-manage.com/subscribe/post?u=0c27354a06a7fdf4d83ce07fc&id=09f634eea4"
  force = true

[[redirects]]
  from = "/tutorial"
  to = "https://learn.redwoodjs.com/docs/tutorial/welcome-to-redwood"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/welcome-to-redwood"
  to = "https://learn.redwoodjs.com/docs/tutorial/welcome-to-redwood"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/welcome-to-redwood.html"
  to = "https://learn.redwoodjs.com/docs/tutorial/welcome-to-redwood"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/prerequisites"
  to = "https://learn.redwoodjs.com/docs/tutorial/prerequisites"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/prerequisites.html"
  to = "https://learn.redwoodjs.com/docs/tutorial/prerequisites"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/installation-starting-development"
  to = "https://learn.redwoodjs.com/docs/tutorial/installation-starting-development"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/installation-starting-development.html"
  to = "https://learn.redwoodjs.com/docs/tutorial/installation-starting-development"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/redwood-file-structure"
  to = "https://learn.redwoodjs.com/docs/tutorial/redwood-file-structure"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/redwood-file-structure.html"
  to = "https://learn.redwoodjs.com/docs/tutorial/redwood-file-structure"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/our-first-page"
  to = "https://learn.redwoodjs.com/docs/tutorial/our-first-page"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/our-first-page.html"
  to = "https://learn.redwoodjs.com/docs/tutorial/our-first-page"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/a-second-page-and-a-link"
  to = "https://learn.redwoodjs.com/docs/tutorial/a-second-page-and-a-link"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/a-second-page-and-a-link.html"
  to = "https://learn.redwoodjs.com/docs/tutorial/a-second-page-and-a-link"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/layouts"
  to = "https://learn.redwoodjs.com/docs/tutorial/layouts"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/layouts.html"
  to = "https://learn.redwoodjs.com/docs/tutorial/layouts"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/getting-dynamic"
  to = "https://learn.redwoodjs.com/docs/tutorial/getting-dynamic"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/getting-dynamic.html"
  to = "https://learn.redwoodjs.com/docs/tutorial/getting-dynamic"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/cells"
  to = "https://learn.redwoodjs.com/docs/tutorial/cells"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/cells.html"
  to = "https://learn.redwoodjs.com/docs/tutorial/cells"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/side-quest-how-redwood-works-with-data"
  to = "https://learn.redwoodjs.com/docs/tutorial/side-quest-how-redwood-works-with-data"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/side-quest-how-redwood-works-with-data.html"
  to = "https://learn.redwoodjs.com/docs/tutorial/side-quest-how-redwood-works-with-data"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/routing-params"
  to = "https://learn.redwoodjs.com/docs/tutorial/routing-params"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/routing-params.html"
  to = "https://learn.redwoodjs.com/docs/tutorial/routing-params"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/everyone-s-favorite-thing-to-build-forms"
  to = "https://learn.redwoodjs.com/docs/tutorial/everyones-favorite-thing-to-build-forms"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/everyone-s-favorite-thing-to-build-forms.html"
  to = "https://learn.redwoodjs.com/docs/tutorial/everyones-favorite-thing-to-build-forms"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/saving-data"
  to = "https://learn.redwoodjs.com/docs/tutorial/saving-data"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/saving-data.html"
  to = "https://learn.redwoodjs.com/docs/tutorial/saving-data"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/administration"
  to = "https://learn.redwoodjs.com/docs/tutorial/administration"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/administration.html"
  to = "https://learn.redwoodjs.com/docs/tutorial/administration"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/authentication"
  to = "https://learn.redwoodjs.com/docs/tutorial/authentication"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/authentication.html"
  to = "https://learn.redwoodjs.com/docs/tutorial/authentication"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/deployment"
  to = "https://learn.redwoodjs.com/docs/tutorial/deployment"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/deployment.html"
  to = "https://learn.redwoodjs.com/docs/tutorial/deployment"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/wrapping-up"
  to = "https://learn.redwoodjs.com/docs/tutorial/wrapping-up"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial/wrapping-up.html"
  to = "https://learn.redwoodjs.com/docs/tutorial/wrapping-up"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/welcome-to-redwood-part-ii-redwood-s-revenge"
  to = "https://learn.redwoodjs.com/docs/tutorial2/welcome-to-redwood-part-ii-redwoods-revenge"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/welcome-to-redwood-part-ii-redwood-s-revenge.html"
  to = "https://learn.redwoodjs.com/docs/tutorial2/welcome-to-redwood-part-ii-redwoods-revenge"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/prerequisites"
  to = "https://learn.redwoodjs.com/docs/tutorial2/prerequisites"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/prerequisites.html"
  to = "https://learn.redwoodjs.com/docs/tutorial2/prerequisites"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/introduction-to-storybook"
  to = "https://learn.redwoodjs.com/docs/tutorial2/introduction-to-storybook"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/introduction-to-storybook.html"
  to = "https://learn.redwoodjs.com/docs/tutorial2/introduction-to-storybook"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/our-first-story"
  to = "https://learn.redwoodjs.com/docs/tutorial2/our-first-story"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/our-first-story.html"
  to = "https://learn.redwoodjs.com/docs/tutorial2/our-first-story"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/our-first-test"
  to = "https://learn.redwoodjs.com/docs/tutorial2/building-a-component-the-redwood-way"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/our-first-test.html"
  to = "https://learn.redwoodjs.com/docs/tutorial2/building-a-component-the-redwood-way"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/building-a-component-the-redwood-way"
  to = "https://learn.redwoodjs.com/docs/tutorial2/building-a-component-the-redwood-way"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/building-a-component-the-redwood-way.html"
  to = "https://learn.redwoodjs.com/docs/tutorial2/building-a-component-the-redwood-way"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/multiple-comments"
  to = "https://learn.redwoodjs.com/docs/tutorial2/multiple-comments"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/multiple-comments.html"
  to = "https://learn.redwoodjs.com/docs/tutorial2/multiple-comments"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/adding-comments-to-the-schema"
  to = "https://learn.redwoodjs.com/docs/tutorial2/adding-comments-to-the-schema"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/adding-comments-to-the-schema.html"
  to = "https://learn.redwoodjs.com/docs/tutorial2/adding-comments-to-the-schema"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/creating-a-comment-form"
  to = "https://learn.redwoodjs.com/docs/tutorial2/creating-a-comment-form"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/creating-a-comment-form.html"
  to = "https://learn.redwoodjs.com/docs/tutorial2/creating-a-comment-form"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/role-based-authorization-control-rbac"
  to = "https://learn.redwoodjs.com/docs/tutorial2/role-based-authorization-control-rbac"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/role-based-authorization-control-rbac.html"
  to = "https://learn.redwoodjs.com/docs/tutorial2/role-based-authorization-control-rbac"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/wrapping-up"
  to = "https://learn.redwoodjs.com/docs/tutorial2/wrapping-up"
  status = 301
  force = true

[[redirects]]
  from = "/tutorial2/wrapping-up.html"
  to = "https://learn.redwoodjs.com/docs/tutorial2/wrapping-up"
  status = 301
  force = true

[[redirects]]
from ="/community"
to ="https://community.redwoodjs.com/t/welcome-to-the-redwoodjs-community/2416"

[[redirects]]
  from = "/docs/redwood-router"
  to = "/docs/router"
  status = 301
  force = true
