# When a PR is merged into the main branch, this workflow opens a PR against the release branch
# with the squashed commit that went into main.

name: üçí Cherry pick into release PR

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  cherry-pick-into-release-pr:
    name: üçí Cherry pick into release PR
    runs-on: ubuntu-latest
    # Don't cherry pick things that are breaking.
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'release:feature-breaking') }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cherry pick into release PR
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.2
        with:
          # We specify a token because we want other workflows (like CI) to run on this PR.
          # If we omit this, it uses the default token (GITHUB_TOKEN) which doesn't trigger other workflows.
          token: ${{ secrets.JTOAR_TOKEN }}
          branch: release
          labels: cherry-pick
