jobs:
  pr_review_requested:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "status: waiting for author"
      - if: failure()
        run: |
          echo "Don't worry if the previous step failed."
          echo "See https://github.com/actions-ecosystem/action-remove-labels/issues/221."

name: PR Review Requested

on:
  pull_request_target:
    types:
      - review_requested

permissions:
  pull-requests: write
