name: Change milestone

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  merge_job:
    # this job only runs when a PR's merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Update milestone to 'next-release'
    permissions:
      pull-requests: write
    steps:
      # to use a private action, you have to check out the repo
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js v12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: cd tasks/actions && yarn install --immutable
      - name: Change milestone to "next-release"
        uses: ./tasks/actions/change-milestone
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          milestone: 'next-release'

  close_job:
    # this job only runs when a PR's closed--without being merged
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    name: Remove milestone
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js v12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: cd tasks/actions && yarn install --immutable
      - name: Remove milestone
        uses: ./tasks/actions/change-milestone
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
