name: ðŸš¢ Publish Release Candidate

on:
  push:
    branches: ['release/**']
    tags-ignore:
      # We don't want this to run on release
      - v**

jobs:
  publish-release-candidate:
    name: ðŸš¢ Publish Release Candidate
    if: github.repository == 'orgtoar/redwood-test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # `fetch-depth`â€”number of commits to fetch. `0` fetches all history for all branches and tags.
          #  This is required because lerna uses tags to determine the version.
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: yarn install

      - name: ðŸ— Build
        run: yarn build

      - name: ðŸ”¬ Lint
        run: yarn lint
        env:
          CI: true

      - name: ðŸ§ª Test
        run: yarn test
        env:
          CI: true

      - name: ðŸš¢ Publish
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
          ./tasks/publish-rc
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
