name: Publish canaray packages to npm

on:
  push:
    branches: [main]
    tags-ignore:
      - v** # We don't want this to run on release

jobs:
  build:
    if: github.repository == 'redwoodjs/redwood'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required because lerna uses tags to determine the version.
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Print node and yarn versions
        run: |
          node --version
          yarn --version

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-1234-${{ hashFiles('yarn.lock') }} #change yarn-{randomString} to bust the cache
          restore-keys: |
            yarn-1234

      - name: Install dependencies
        run: yarn install --immutable

      - name: Determine if the PR only changed docs
        id: only_changed_docs
        uses: ./.github/actions/only_changed_docs

      - name: 'Check Yarn constraints (fix w/ "yarn constraints --fix")'
        if: fromJSON(steps.only_changed_docs.outputs.only_changed_docs) == false
        run: yarn constraints

      - name: 'Check for duplicate dependencies (fix w/ "yarn dedupe")'
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn dedupe --check

      - name: Build
        if: fromJSON(steps.only_changed_docs.outputs.only_changed_docs) == false
        run: yarn build

      - name: Run ESLint
        if: fromJSON(steps.only_changed_docs.outputs.only_changed_docs) == false
        run: yarn lint
        env:
          CI: true

      - name: Run tests
        if: fromJSON(steps.only_changed_docs.outputs.only_changed_docs) == false
        run: yarn test
        env:
          CI: true

      - name: Publish to npm
        if: fromJSON(steps.only_changed_docs.outputs.only_changed_docs) == false
        run: |
          git describe
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
          yarn publish:canary
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
