name: ğŸ§ª Publish Experimental

on:
  push:
    branches: ['experimental/*']
    # No need to run on docs-only changes
    paths-ignore: ['docs/**']

# Cancel in-progress runs of this workflow.
# See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-experimental:
    name: ğŸ§ª Publish Experimental
    if: github.repository == 'redwoodjs/redwood'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.value }}
    steps:
      - uses: actions/checkout@v3
        # `fetch-depth`â€”number of commits to fetch. `0` fetches all history for all branches and tags.
        #  This is required because lerna uses tags to determine the version.
        with:
          fetch-depth: 0

      - name: ğŸ§¶ Set up job
        uses: ./.github/actions/set-up-job

      - name: âœ… Check constraints, dependencies, and package.json's
        uses: ./tasks/check

      - name: ğŸ— Build
        run: yarn build

      - name: ğŸ” Lint
        run: yarn lint

      - name: ğŸ§ª Test
        run: yarn test

      - name: ğŸš¢ Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc

          TAG="experimental-$(basename ${{ github.ref_name }})"

          echo "Publishing $TAG"

          yarn lerna publish premajor --include-merged-tags \
                                      --canary \
                                      --exact \
                                      --preid "$TAG" \
                                      --dist-tag "$TAG" \
                                      --force-publish \
                                      --loglevel verbose \
                                      --no-git-reset \
                                      --yes

        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: ğŸ· Get version
        id: get-version
        uses: sergeysova/jq-action@v2.3.0
        with:
          cmd: 'jq .version packages/core/package.json -r'

  message-slack:
    name: ğŸ’¬ Message Slack
    needs: publish-experimental
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: ğŸ’¬ Message Slack
        uses: ./.github/actions/message_slack_publishing
        with:
          title: "ğŸ§ª Experimental Packages"
          status: ${{ needs.publish-canary.result }}
          version: ${{ needs.publish-canary.outputs.version }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_PACKAGE_PUBLISHING }}
