name: ðŸš¢ Publish Canary

on:
  push:
    branches: [main]
    tags-ignore:
      # We don't want this to run on release
      - v**
    paths-ignore:
      # We don't want this to run on changes to docs
      - 'docs/**'

jobs:
  publish-canary:
    name: ðŸš¢ Publish Release Candidate
    if: github.repository == 'redwoodjs/redwood'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # `fetch-depth`â€”number of commits to fetch. `0` fetches all history for all branches and tags.
          #  This is required because lerna uses tags to determine the version.
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          # Change yarn-{randomString} to bust the cache.
          key: yarn-1234-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-1234

      - run: yarn install

      - name: 'âœ… Check Yarn constraints (fix with `yarn constraints --fix`)'
        run: yarn constraints

      - name: 'âœ… Check for duplicate dependencies (fix with `yarn dedupe`)'
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn dedupe --check

      - name: ðŸ— Build
        run: yarn build

      - name: ðŸ”¬ Lint
        run: yarn lint
        env:
          CI: true

      - name: ðŸ§ª Test
        run: yarn test
        env:
          CI: true

      - name: ðŸš¢ Publish
        run: |
          git describe
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
          yarn publish:canary
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
