name: ğŸ’ Cherry pick commit into PR against release

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  cherry-pick-commit-into-pr-against-release:
    runs-on: ubuntu-latest
    name: ğŸ’ Cherry pick commit into PR against release

    if: ${{ !contains(github.event.pull_request.labels.*.name, 'release:feature-breaking') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cherry pick into release
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          token: ${{ secrets.JTOAR_TOKEN }}
          branch: release
          labels: cherry-pick
