name: Release PR

on:
  pull_request:
    branches:
      - main
    types: ["closed"]


jobs:
  release_pr:
    runs-on: ubuntu-latest
    name: release_pr

    if: ${{ !contains(github.event.pull_request.labels.*.name, 'release:feature-breaking') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cherry pick into next
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: next
          labels: |
            cherry-pick
          reviewers: |
            jtoar
